
database:
  url: jdbc:mysql://${MYSQL_HOST:-localhost}:3306/stock
  user-name: lw
  password: lw
  driver-class-name: com.mysql.cj.jdbc.Driver

resumeAdjustment:
  initialDelay: 15000
  fixedDelay: 30000

adjustmentUpdate:
  initialDelay: 10000
  fixedDelay: 5000

cost:
  stockURI: 'http://192.168.0.80:5495/sdata/accounts50/GCRM/%7B158156F0-396C-4FA9-AD17-F4A27F82A47D%7D/commodities'
  stockLevels: '?select=reference,name,inStock,allocated,freestock,onOrder,salesPrice&format=json&where=reference in '
  password: ''
  user: 'Helen'
  getCostPrice: true

email:
  senderEmail: info@lewisandwood.co.uk
  receiverEmail: paul.soule@gmail.com
  subject: StockSys Alert
  apiKey: f8049f6f-dec7-49b0-bf1f-cc10119cd916

stock:
  uri: 'https://157.231.105.106:40027/api/stock'
  api_key: 'ngEXJVHb4mHYvr2tuNTsjBNz'

adjustments:
  adjustmentTimeout: 30
  maximumErrors: 3
  pausePeriod: 60